export default {
  beforeStart: 'Antes de empezar', intro: 'Cuatro respuestas nos ayudan a configurar Treseko según tu forma de trabajo.', role: 'Rol principal', organization: 'Tamaño de organización', expectedUse: 'Uso esperado', currentFlow: 'Herramienta o flujo actual', chooseMultiple: 'Puedes elegir más de uno.',
  terms: 'Acepto los términos y condiciones de Treseko.', telemetry: 'Quiero compartir estas respuestas anónimas para ayudar a mejorar Treseko.', telemetryHint: 'Nos ayuda a priorizar integraciones, onboarding y reportes. Es opcional: Treseko funciona igual si no lo marcas. No se envía email, nombre ni IDs de proyecto. Puedes revisar los términos en', continue: 'Continuar',
  guideTitle: 'Cómo se ordena Treseko', guideIntro: 'Una guía visual rápida para entender la jerarquía de trabajo.', solution: 'Solución', project: 'Proyecto', component: 'Componente', build: 'Build', cases: 'Casos', reports: 'Reportes', previous: 'Anterior', next: 'Siguiente', start: 'Empezar', guideTip: 'Cada usuario ve esta guía una sola vez. Luego podrás volver a orientarte desde la estructura de navegación.',
  roleManual: 'QA manual', roleAutomation: 'QA automation', roleLead: 'QA lead', roleDev: 'Dev/DevOps', roleProduct: 'Producto/Gestión', other: 'Otro',
  useCases: 'gestionar casos', useExecute: 'ejecutar pruebas', useAutomation: 'automatización', useBugs: 'bugs/evidencias', useReports: 'reportes',
  toolNone: 'Nada / proceso informal', toolExcel: 'Excel / Sheets', toolJira: 'Jira', toolGithub: 'GitHub Issues', toolTestRail: 'TestRail / Zephyr / Xray', toolAutomation: 'Herramientas de automatización',
  guideSolutions: 'Soluciones', guideSolutionsText: 'Agrupan clientes, equipos o líneas de negocio. Es el primer contenedor donde vive tu trabajo QA.', guideClient: 'Cliente', guideTeam: 'Equipo', guideQaUnit: 'Unidad QA',
  guideProjects: 'Proyectos', guideProjectsText: 'Cada proyecto representa un producto, app o iniciativa que necesita pruebas, bugs y reportes propios.', guideProduct: 'Producto', guideApp: 'Aplicación', guideInitiative: 'Iniciativa',
  guideComponents: 'Componentes y Builds', guideComponentsText: 'Los componentes separan módulos. Las builds son versiones concretas: ahí asignas casos y decides si una entrega está lista.', guideModule: 'Módulo', guideVersion: 'Versión', guideRelease: 'Release',
  guideSuites: 'Suites, ejecuciones y reportes', guideSuitesText: 'Ordena casos en suites, ejecuta pruebas, adjunta evidencia, reporta bugs y comparte métricas de la build.', guideCases: 'Casos', guideEvidence: 'Evidencias', guideReports: 'Reportes',
  savePreferencesError: 'No se pudieron guardar tus preferencias.', telemetryError: 'No se pudieron enviar las respuestas.', initialConfigError: 'No se pudo guardar la configuración inicial.', surveyError: 'No se pudo guardar la encuesta.', closeGuideError: 'No se pudo cerrar la guía.',
} as const
