import { useExecutionPreparation } from "../features/ejecutar-pruebas/hooks/useExecutionPreparation";
import { createEjecucionActionBundle } from "../features/ejecucion/ejecucionActionBundle";
export function useAppExecutionActions({ options }: { options: any }) {
  const { canAccessCapability } = options;
  const { activeExecutionCaseIds,activeTab,aiEngineConfig,attachmentConfig,buildCaseIds,buildCaseResultHistoryByBuild,buildCasesLoadingByBuild,buildsList,casosList,casosLoading,componentsList,currentBuildId,currentCompId,currentExecutionCase,currentExecutionRun,currentProjectCases,currentProjectId,executionModalCaseIds,executionSnapshots,fetchWithAuth,generalExecutionAttachments,generalExecutionNote,generalExecutionSnapshot,generalExecutionStatus,latestResultsLoadingByBuild,loadBuildCaseExecutionStatus,loadBuildCases,loadCasoExecutionHistory,loadCasosFromBackend,managingProjectId,mapBackendCasoToTest,redmineDecisionByExecution,selectSuiteTarget,selectedExecutionDatasetId,selectedExecutionEnvironmentId,selectedExecutionTestIds,selectedSubSuiteId,selectedSuiteId,selectedTest,setActiveExecutionCaseIds,setActiveTab,setAutomationMonitor,setBuildCaseIds,setBuildCaseResultHistoryByBuild,setCasosList,setCurrentExecutionCase,setCurrentExecutionRun,setExecName,setExecutionDatasetPreview,setExecutionDatasetPreviewLoading,setExecutionLoading,setExecutionModalCaseIds,setExecutionMode,setExecutionSnapshots,setGeneralExecutionAttachments,setGeneralExecutionNote,setGeneralExecutionSnapshot,setGeneralExecutionStatus,setIaExecutionStreams,setIaLogs,setIaQueue,setProjectSyncMessage,setRedmineBugs,setRedmineDecisionByExecution,setScheduledTime,setSchedulerSearch,setSelectedExecutionTestIds,setSelectedSubSuiteId,setSelectedSuiteId,setSelectedTest,setSelectedTestsForIa,setShowExecSelector,setShowIaScheduler,setShowRedmineDrawer,setShowRedminePrompt,setSnapshotAttachments,setSnapshotNotes,setStepResults,setViewMode,showExecSelector,showFeedback,snapshotAttachments,snapshotNotes,stepResults,suitesLoading,suitesTree,t,testSearchQuery,viewMode,visibleSuiteTree
 } = options;
  const executionPreparation = useExecutionPreparation({
    activeTab,
    currentBuildId,
    currentCompId,
    currentProjectId,
    currentProjectCases,
    suitesTree,
    visibleSuiteTree,
    buildCaseIds,
    buildCaseResultHistoryByBuild,
    latestResultsLoadingByBuild,
    buildCasesLoadingByBuild,
    suitesLoading,
    casosLoading,
    selectedSubSuiteId,
    selectedSuiteId,
    testSearchQuery,
    selectedExecutionTestIds,
    executionModalCaseIds,
    activeExecutionCaseIds,
    selectedTest,
    showExecSelector,
    selectedExecutionEnvironmentId,
    selectedExecutionDatasetId,
    setExecutionDatasetPreview,
    setExecutionDatasetPreviewLoading,
    fetchWithAuth,
    casosList,
    selectSuiteTarget,
    setSelectedSuiteId,
    setSelectedSubSuiteId,
    setSelectedTest,
    setSelectedExecutionTestIds,
    setExecutionModalCaseIds,
    setShowExecSelector,
    setSelectedTestsForIa,
    setSchedulerSearch,
    setExecName,
    setScheduledTime,
    setShowIaScheduler,
    showFeedback,
  });

  const { activeBuildCaseIds, activeExecutionTests, executionModalTests, executionModalDiscardedCount, isOutdatedExecutionCase, getExecutionCaseLabel } = executionPreparation;
  const executionActions = createEjecucionActionBundle({
    t,
    managingProjectId,
    currentProjectId,
    currentBuildId,
    currentCompId,
    selectedExecutionEnvironmentId,
    selectedExecutionDatasetId,
    buildsList,
    buildCaseIds,
    currentProjectCases,
    selectedTest,
    activeExecutionTests,
    currentExecutionRun,
    currentExecutionCase,
    activeBuildCaseIds,
    componentsList,
    executionSnapshots,
    stepResults,
    snapshotNotes,
    snapshotAttachments,
    attachmentConfig,
    generalExecutionStatus,
    generalExecutionNote,
    generalExecutionSnapshot,
    generalExecutionAttachments,
    redmineDecisionByExecution,
    viewMode,
    executionModalTests,
    executionModalDiscardedCount,
    canUseAutomatedExecution:
      canAccessCapability("ejecutar.automatizada", "edit") &&
      canAccessCapability("automatizacion.workers", "read"),
    fetchWithAuth,
    mapBackendCasoToTest,
    isOutdatedExecutionCase,
    getExecutionCaseLabel,
    loadBuildCaseExecutionStatus,
    setCasosList,
    setBuildCaseResultHistoryByBuild,
    setBuildCaseIds,
    setCurrentExecutionCase,
    setExecutionSnapshots,
    setSnapshotAttachments,
    setGeneralExecutionSnapshot,
    setGeneralExecutionAttachments,
    setStepResults,
    setSnapshotNotes,
    setGeneralExecutionStatus,
    setGeneralExecutionNote,
    setExecutionLoading,
    setCurrentExecutionRun,
    setExecutionMode,
    setSelectedTest,
    setActiveExecutionCaseIds,
    setExecutionModalCaseIds,
    setShowExecSelector,
    setViewMode,
    setIaQueue,
    setIaExecutionStreams,
    setIaLogs,
    setActiveTab,
    setAutomationMonitor,
    aiEngineConfig,
    setProjectSyncMessage,
    loadCasoExecutionHistory,
    loadCasosFromBackend,
    loadBuildCases,
    setRedmineDecisionByExecution,
    setShowRedminePrompt,
    setShowRedmineDrawer,
    setRedmineBugs,
    showFeedback,
  });

  return { ...executionPreparation, ...executionActions };
}
