export type BackendStatus = 'PASO' | 'FALLO' | 'BLOQUEADO';

export type StrictActionName =
  | 'navigate'
  | 'click'
  | 'click_at'
  | 'type'
  | 'fill_form'
  | 'check'
  | 'select'
  | 'press'
  | 'wait'
  | 'assert_visible'
  | 'assert_text'
  | 'finish'
  | 'fail'
  | 'blocked';

export interface QAEngineStep {
  number: number;
  action?: string;
  data?: string;
  expected?: string;
  /**
   * Ephemeral execution-only validation plan. It is generated by the engine
   * for this run and is never written back to the test case.
   */
  validation_plan?: RuntimeStepValidationPlan;
}

export type StepAssertionType =
  | 'text_contains'
  | 'text_contains_any'
  | 'element_contains'
  | 'element_visible'
  | 'element_value'
  | 'url_matches'
  | 'url_not_matches'
  | 'url_changed'
  | 'http_status'
  | 'json_field_equals'
  | 'element_count'
  | 'field_required'
  | 'option_selected'
  | 'checkbox_checked'
  | 'button_enabled'
  | 'images_loaded';

export interface StepAssertion {
  id: string;
  type: StepAssertionType;
  source: string;
  target?: string;
  expected?: string | number | boolean;
  alternatives?: string[];
  comparator?: 'equals' | 'at_least';
}

export type RuntimeValidationMode = 'dom' | 'visual_semantic' | 'manual_review';

export interface RuntimeStepValidationPlan {
  mode: RuntimeValidationMode;
  assertions: Omit<StepAssertion, 'id'>[];
  reason: string;
  confidence: number;
  source: 'rules' | 'ai';
}

export interface StepContract {
  version: 1;
  step_number: number;
  assertions: StepAssertion[];
  recognized_fragments: string[];
  unresolved_fragments: string[];
  coverage: 'full' | 'partial' | 'none';
  requires_semantic_audit: boolean;
}

export interface StepAssertionResult {
  assertion: StepAssertion;
  ok: boolean;
  reason: string;
}

export interface ExecutionCheckpoint {
  step_number: number;
  attempt: number;
  created_at: string;
  url: string;
  title: string;
  ready_state: string;
  visible_text_excerpt: string[];
  assertion_results: StepAssertionResult[];
  contract_coverage: StepContract['coverage'];
  screenshot_available: boolean;
  recoverable: boolean;
}

export interface BrowserElementSnapshot {
  ref: string;
  tag: string;
  role?: string;
  name?: string;
  text?: string;
  value?: string;
  type?: string;
  placeholder?: string;
  label?: string;
  title?: string;
  disabled: boolean;
  checked?: boolean;
  required?: boolean;
  valid?: boolean;
  validationMessage?: string;
  selectedValues?: string[];
  imageComplete?: boolean;
  naturalWidth?: number;
  naturalHeight?: number;
  visible: boolean;
  editable: boolean;
  clickable: boolean;
  bbox?: { x: number; y: number; width: number; height: number };
}

export interface BrowserObservation {
  url: string;
  title: string;
  readyState: string;
  viewport?: { width: number; height: number };
  loadingSignals: string[];
  dialogs: string[];
  visibleText: string[];
  bodyText: string;
  elements: BrowserElementSnapshot[];
  forms: Array<{ ref: string; fields: string[] }>;
}

export interface StrictAIAction {
  action: StrictActionName;
  target_ref?: string;
  x?: number;
  y?: number;
  value?: string;
  fields?: Array<{ target_ref: string; value: string }>;
  submit_after_type?: boolean;
  reason: string;
  expected?: string;
  confidence: number;
  step_number: number;
}

export interface ActionExecutionResult {
  ok: boolean;
  command: string;
  message: string;
  error?: string;
}

export interface StructuredHistoryItem {
  step_number: number;
  attempt: number;
  observation_before: Pick<BrowserObservation, 'url' | 'title' | 'readyState' | 'loadingSignals'>;
  observation_after?: Pick<BrowserObservation, 'url' | 'title' | 'readyState' | 'loadingSignals' | 'visibleText' | 'bodyText'>;
  action: StrictAIAction;
  execution: ActionExecutionResult;
  duration_ms: number;
  screenshot_base64?: string;
  metrics?: Record<string, unknown>;
  validation?: {
    ok: boolean;
    reason: string;
    conclusive?: boolean;
  };
  post_validation?: {
    ok: boolean;
    reason: string;
    conclusive?: boolean;
  };
  raw_ai_response?: unknown;
  contract?: StepContract;
  checkpoint?: ExecutionCheckpoint;
}

export interface StepRunResult {
  number: number;
  status: BackendStatus;
  observations?: string;
  error_log?: string;
  screenshot_base64?: string;
  history: StructuredHistoryItem[];
  confidence?: number;
  failure_category?: string;
  agent?: string;
  reason?: string;
  action_summary?: string;
  action_executed?: boolean;
  url?: string;
  contract?: StepContract;
  checkpoints?: ExecutionCheckpoint[];
}
