import { useMemo } from 'react'

export function useReportDataModel(options: any) {
  const { projectMetrics, detailFilters, sharedReportHistory, showFullSharedHistory, t } = options
  const suiteTree = projectMetrics?.por_suite_tree?.length ? projectMetrics.por_suite_tree : Object.entries(projectMetrics?.por_suite || {}).map(([id, data]: [string, any]) => ({ id, ...data, children: [] }))
  const aiMetrics = projectMetrics?.ai_metrics || {}; const bugMetrics = projectMetrics?.bug_metrics || {}; const buildContext = projectMetrics?.build_context || {}; const qaStatus = projectMetrics?.qa_status || {}; const temporalMetrics = projectMetrics?.temporal_metrics || {}; const bugTraceability = projectMetrics?.bug_traceability || {}
  const failureItems = projectMetrics?.failures_and_blockers || []; const evidenceItems = projectMetrics?.evidence_items || []; const evidenceSummary = projectMetrics?.evidence_summary || {}; const comparison = projectMetrics?.comparison || {}; const reportStats = projectMetrics?.stats || {}
  const formatInt = (value: any) => Number(value || 0).toLocaleString()
  const formatPercent = (value: any) => `${Number(value || 0).toFixed(1)}%`
  const formatHours = (value: any) => { if (value === null || value === undefined || value === '') return 'N/D'; const hours = Number(value || 0); if (hours < 1) return `${Math.round(hours * 60)} min`; if (hours < 48) return `${hours.toFixed(1)} h`; return `${(hours / 24).toFixed(1)} dias` }
  const formatSeconds = (value: any) => { const seconds = Number(value || 0); if (!seconds) return '0 min'; if (seconds < 60) return `${seconds}s`; if (seconds < 3600) return `${Math.round(seconds / 60)} min`; return `${(seconds / 3600).toFixed(1)} h` }
  const riskVariant = (risk: any) => { const normalized = String(risk || '').toUpperCase(); if (['ALTO', 'ALTA', 'CRITICA', 'CRITICO', 'P0', 'P1'].includes(normalized)) return 'danger'; if (['MEDIO', 'MEDIA', 'P2'].includes(normalized)) return 'warning'; return 'success' }
  const statusVariant = (state: any) => { const normalized = String(state || '').toUpperCase(); if (normalized === 'BLOQUEADO' || normalized === 'NO_RECOMENDADO') return 'danger'; if (normalized === 'RECOMENDADO_CON_OBSERVACIONES' || normalized === 'EN_EVALUACION') return 'warning'; return 'success' }
  const displayedSharedHistory = showFullSharedHistory ? sharedReportHistory : sharedReportHistory.slice(0, 5)
  const uniqueOptions = (items: any[], getter: (item: any) => any) => Array.from(new Set(items.map(getter).filter((value) => value !== null && value !== undefined && String(value).trim() !== '').map((value) => String(value)))).sort((a, b) => a.localeCompare(b))
  const allReportBugs = projectMetrics?.bugs || []; const suiteFilterOptions = uniqueOptions([...allReportBugs, ...failureItems], (item) => item.suite); const priorityFilterOptions = uniqueOptions([...allReportBugs, ...failureItems], (item) => item.prioridad); const ownerFilterOptions = uniqueOptions([...allReportBugs, ...failureItems], (item) => item.responsable)
  const matchesDetailFilters = (item: any, kind: 'bug' | 'failure' | 'evidence') => {
    const suite = String(item.suite || ''), priority = String(item.prioridad || ''), status = String(item.estado || item.status || ''), owner = String(item.responsable || item.created_by || ''), mode = String(item.execution_mode || '')
    const hasBug = kind === 'bug' ? true : Array.isArray(item.bug) ? item.bug.length > 0 : Boolean(item.bug); const bugIsOpen = kind === 'bug' ? item.is_open !== false : true; const hasEvidence = kind === 'bug' ? Boolean(item.has_evidence) : kind === 'evidence' ? item.status === 'completa' : !item.flags?.sin_evidencia
    return (!detailFilters.suite || suite === detailFilters.suite) && (!detailFilters.priority || priority === detailFilters.priority) && (!detailFilters.status || status === detailFilters.status) && (!detailFilters.owner || owner === detailFilters.owner) && (!detailFilters.executionMode || mode === detailFilters.executionMode) && (!detailFilters.bug || (kind === 'bug' ? detailFilters.bug === 'open' ? bugIsOpen : detailFilters.bug === 'closed' ? !bugIsOpen : true : detailFilters.bug === 'with' ? hasBug : detailFilters.bug === 'without' ? !hasBug : true)) && (!detailFilters.evidence || (detailFilters.evidence === 'with' ? hasEvidence : !hasEvidence))
  }
  const filteredReportBugs = allReportBugs.filter((item: any) => matchesDetailFilters(item, 'bug')); const filteredFailures = failureItems.filter((item: any) => matchesDetailFilters(item, 'failure')); const filteredEvidenceItems = evidenceItems.filter((item: any) => matchesDetailFilters(item, 'evidence'))
  const bugStatusIsOpen = (status: any) => !['RESUELTO', 'CERRADO', 'DUPLICADO', 'NO_REPRODUCIBLE', 'NO_CORRESPONDE'].includes(String(status || '').toUpperCase())
  const formatMoney = (value: any) => `$${Number(value || 0).toFixed(5)}`; const formatMs = (value: any) => { const ms = Number(value || 0); if (!ms) return '0ms'; if (ms >= 1000) return `${(ms / 1000).toFixed(1)}s`; return `${ms}ms` }
  const aiModels = Object.entries(aiMetrics.models || {}).sort((a: any, b: any) => Number(b[1]) - Number(a[1])); const aiFailureCategories = Object.entries(aiMetrics.failure_categories || {}).sort((a: any, b: any) => Number(b[1]) - Number(a[1])); const aiErrorCodes = Object.entries(aiMetrics.error_codes || {}).sort((a: any, b: any) => Number(b[1]) - Number(a[1]))
  const readableAiLabel = (value: any) => { const raw = String(value || '').trim(); const labels: Record<string, string> = { blocked_by_engine: 'Bloqueado por el motor', target_not_found: 'Objetivo no encontrado', validation_failed: 'Validacion fallida', timeout: 'Tiempo agotado', navigation_failed: 'Navegacion fallida', unknown: 'Sin clasificar', AI_HUMAN_REVIEW_REQUIRED: 'Requiere revision humana', TARGET_NOT_FOUND: 'Objetivo no encontrado', VALIDATION_FAILED: 'Validacion fallida', TIMEOUT: 'Tiempo agotado', NAVIGATION_FAILED: 'Navegacion fallida' }; if (labels[raw]) return labels[raw]; return raw.replace(/^AI_/, '').replace(/[_-]+/g, ' ').toLowerCase().replace(/\b\w/g, char => char.toUpperCase()) }
  const pendingStatus = Number(reportStats.pendientes || 0); const statusChartData = [{ name: 'Pasados', value: Number(reportStats.pasados || 0), color: '#198754' }, { name: 'Fallados', value: Number(reportStats.fallados || 0), color: '#dc3545' }, { name: 'Bloqueados', value: Number(reportStats.bloqueados || 0), color: '#0d6efd' }, { name: 'Sin ejecutar', value: pendingStatus, color: '#6c757d' }].filter(item => item.value > 0)
  const executionModeMetrics = projectMetrics?.por_modo_ejecucion || projectMetrics?.por_tipo_ejecucion || {}; const executionModeData = [{ name: 'Manual', cantidad: Number(executionModeMetrics.manual || 0), fill: '#6c757d' }, { name: 'IA', cantidad: Number(executionModeMetrics.ia || executionModeMetrics.automatizada_ia || 0), fill: '#0d6efd' }, { name: 'Automatizada', cantidad: Number(executionModeMetrics.automatizada || 0), fill: '#6f42c1' }, { name: 'Externa', cantidad: Number(executionModeMetrics.externa || 0), fill: '#198754' }]
  const caseTypeMetrics = projectMetrics?.por_tipo_prueba || {}; const caseTypeData = [{ name: 'Manual', cantidad: Number(caseTypeMetrics.manual || 0) }, { name: 'Automatizada', cantidad: Number(caseTypeMetrics.automatizada || 0) }, { name: 'Automatizada IA', cantidad: Number(caseTypeMetrics.automatizada_ia || 0) }].filter(item => item.cantidad > 0)
  const executedStatusTotal = Number(reportStats.pasados || 0) + Number(reportStats.fallados || 0) + Number(reportStats.bloqueados || 0); const assignedStatusTotal = Number(projectMetrics?.total_casos_asignados || (executedStatusTotal + pendingStatus)); const statusChartTotal = statusChartData.reduce((sum, item) => sum + item.value, 0); let statusCursor = 0
  const statusGradient = statusChartData.length === 1 ? statusChartData[0].color : `conic-gradient(${statusChartData.map(item => { const start = statusCursor; statusCursor += statusChartTotal > 0 ? (item.value / statusChartTotal) * 100 : 0; return `${item.color} ${start}% ${statusCursor}%` }).join(', ')})`
  const executionModeMax = Math.max(1, ...executionModeData.map(item => item.cantidad)); const hasExecutionModeData = executionModeData.some(item => item.cantidad > 0); const workflowNodeSummary = Number(aiMetrics.workflow_custom_nodes_configured || 0) > 0 ? `${formatInt(aiMetrics.workflow_base_nodes_configured)} base + ${formatInt(aiMetrics.workflow_custom_nodes_configured)} custom` : `${formatInt(aiMetrics.workflow_nodes_configured)} nodos configurados`
  return { suiteTree, aiMetrics, bugMetrics, buildContext, qaStatus, temporalMetrics, bugTraceability, failureItems, evidenceItems, evidenceSummary, comparison, reportStats, formatInt, formatPercent, formatHours, formatSeconds, riskVariant, statusVariant, displayedSharedHistory, uniqueOptions, allReportBugs, suiteFilterOptions, priorityFilterOptions, ownerFilterOptions, matchesDetailFilters, filteredReportBugs, filteredFailures, filteredEvidenceItems, bugStatusIsOpen, formatMoney, formatMs, aiModels, aiFailureCategories, aiErrorCodes, readableAiLabel, pendingStatus, statusChartData, executionModeData, caseTypeData, executedStatusTotal, assignedStatusTotal, statusChartTotal, statusGradient, executionModeMax, hasExecutionModeData, workflowNodeSummary }
}
